- project:
    templates:
      - check-requirements
      - release-notes-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
