- project:
    templates:
      - check-requirements
      - release-notes-jobs-python3
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
