[tox]
minversion = 4.28.0
envlist = py3,pep8
skipsdist = True

[testenv]
usedevelop = True
constraints =
  {env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
# Install also sitemap scraping tool, not installed by default
# therefore not in requirements file
deps =
  scrapy>=2.19.0
  -r{toxinidir}/test-requirements.txt
  -r{toxinidir}/requirements.txt
commands = stestr run --slowest {posargs}

[testenv:pep8]
deps =
  pre-commit
commands =
  pre-commit run -a

[testenv:releasenotes]
commands =
  sphinx-build -a -E -W -d releasenotes/build/doctrees --keep-going -b html releasenotes/source releasenotes/build/html

[testenv:sitemap]
# commands = functional test command goes here

[testenv:venv]
commands = {posargs}

[testenv:docs]
commands =
  sphinx-build -W --keep-going -b html -d doc/build/doctrees doc/source doc/build/html

[testenv:bindep]
# Do not install any requirements. We want this to be fast and work even if
# system dependencies are missing, since it's used to tell you what system
# dependencies are missing! This also means that bindep must be installed
# separately, outside of the requirements files, and develop mode disabled
# explicitly to avoid unnecessarily installing the checked-out repo too (this
# further relies on "tox.skipsdist = True" above).
deps = bindep
commands = bindep test
usedevelop = False

[flake8]
show-source = True
builtins = _
exclude=.venv,.git,.tox,dist,*lib/python*,*egg,build,doc/source/conf.py
# 28 is currently the most complex thing we have
max-complexity=29
ignore = H101
